### ISSUE TITLE
Add more kernel functions

### ISSUE THREAD

**Issue by seatonullberg** [seatonullberg/kernel-density-estimation#1]
All the kernel functions described [here](https://en.wikipedia.org/wiki/Kernel_(statistics)) should be implemented.

- [x] Uniform
- [x] Triangular
- [x] Epanechnikov
- [x] Quartic
- [x] Triweight
- [x] Tricube
- [x] Normal (Gaussian)
- [x] Cosine
- [x] Logistic
- [x] Sigmoid
- [x] Silverman

**Comment by ndcroos** [comment]
Hi, I'd like to work further on this issue.

**Comment by seatonullberg** [comment]
@ndcroos Thanks for the pull request! I have been too busy with my research to review this, but I intend to get to it soon.

**Comment by wangjiawen2013** [comment]
@seatonullberg
Hope you can merge the request to keep this crate alive, which is very helpful !

**Comment by seatonullberg** [comment]
Sorry this took me almost a year to get to. Thanks again @ndcroos I really appreciate it!
